### ISSUE TITLE
Checking If Images Are Loaded

### ISSUE THREAD

**Issue by elky** [AllThingsSmitty/jquery-tips-everyone-should-know#15]
This is more tricky as you think. `$.load` method doesn't work (at least not in every browser) with cached images.

**Comment by smoqadam** [comment]
:+1: 
You can use the following snippet in top of your script to disable cache : 
```javascript
$.ajaxSetup ({
    cache: false
});
```

**Comment by chriskonnertz** [comment]
> Even if you don't have any broken links, adding this won't do any harm.

Well it can do a lot of harm if the "rescue image" is not available as well: infinite loop incoming.

**Comment by cmarfil** [comment]
haha, yeah @chriskonnertz, you're absolutely right.

**Solution**
```javascript
$('img').on('error', function () {
	if(!$(this).hasClass('broken-image')){
		$(this).prop('src', 'img/broken.png');
		$(this).addClass('broken-image');
	}
});
```

**Comment by chriskonnertz** [comment]
Good idea!

**Comment by mplungjan** [comment]
Where would you add this code? Before the img tags? Then they do not exist in Dom- after the img tags, if they have arc attributes their load and error handlers likely already triggered.

**Comment by jakeparis** [comment]
@smoqadam Why would you want to invalidate your cache just to check if an image is loaded? That's a waste of bandwidth. A better way is
```
var onLoadedFunction = function(){
   // do something
});
if ( $('img')[0].loaded ) {
   onLoadedFunction();
} else  {
   $('img').load(function(){
   onLoadedFunction();
});
```

This way you're checking if the image is already loaded, and only if it's not, then you're setting up the load handler.
