### ISSUE TITLE
Open External Links in New Tab/Window

### ISSUE THREAD

**Issue by pelletized** [AllThingsSmitty/jquery-tips-everyone-should-know#16]
A small note about window.location.origin, it does not work in IE 10 (and below?). A quick fix for that can be found here: http://tosbourn.com/a-fix-for-window-location-origin-in-internet-explorer/

This just came up for me yesterday so it's been on my mind! Thanks for putting this list together, it's really great!

**Comment by AllThingsSmitty** [comment]
@pelletized thanks for catching that. I'll get that added. Much appreciated.

**Comment by AllThingsSmitty** [comment]
Fixed with https://github.com/AllThingsSmitty/jquery-tips-everyone-should-know/commit/57ce4cf2d616643dd59beda1766b16ccd0faefbb.
