### ISSUE TITLE
Ajax calls enhancement

### ISSUE THREAD

**Issue by leroy0211** [AllThingsSmitty/jquery-tips-everyone-should-know#26]
When using an Ajax call, always use an error handler! 
When an ajax call returns a 404 or 500 error, the error handler will be executed. If the handler is not defined, sometimes other javascript/jquery wont work anymore.  I'm not sure if this is the case with jquery 2, but I have seen this problem before.

You can define a global ajax error handler in jquery by:

```javascript
$(document).ajaxError(function(e, xhr, settings, error){
    console.log(error);
});
```

**Comment by AllThingsSmitty** [comment]
@leroy0211 excellent idea, thanks!
