### ISSUE TITLE
Crossbrowsing toTop

### ISSUE THREAD

**Issue by Fakkio84** [AllThingsSmitty/jquery-tips-everyone-should-know#37]
I think the right way to do toTop animation is through the selector $('html, body') for crossbrowsing purpose, i.e.:
```javascript
$(document.body).animate({scrollTop: 0}, 800);
```

**Comment by mynamesleon** [comment]
+1 for this. Need to use `$('html, body')` for IE7 & 8 support

**Comment by AllThingsSmitty** [comment]
Thanks, I'm [reviewing this](https://github.com/jquery/api.jquery.com/issues/417) now.

**Comment by AllThingsSmitty** [comment]
Commit https://github.com/AllThingsSmitty/jquery-tips-everyone-should-know/commit/bbec1d5a4fb0cb1ad59c6e15160e0fb5574daf49.
