### ISSUE TITLE
Few jQuery tips inside your tips!

### ISSUE THREAD

**Issue by cmocho** [AllThingsSmitty/jquery-tips-everyone-should-know#38]
Hey, sorry to raise this like an "issue", I didn't seem to find anywhere else to send you this message...

For the "Make two (or more) DIVs the same height" for example, you could use a much smaller version of code if you use Math and Array.map (in this case the "map" function that jQuery provides). Like this:

var maxHeight = Math.max.apply(null, ($("div").map(function(){ return $(this).height(); })));
$("div").height(maxHeight);

As you can see, jQuery also doesn't need you to iterate through the nodes to set their properties, you can set the property for a selection of nodes, all at once.

Hope this is helpful! 

Regards,
Cristian.

**Comment by AllThingsSmitty** [comment]
That's a great tip. Thanks for sharing, I think it makes a nice alternative.

**Comment by AllThingsSmitty** [comment]
I tried this but don't get a result where the divs are equal height. Do you have a working demo?

**Comment by cmocho** [comment]
Probably because of some style differences, inherent to the way the browsers render things on the screen, you might see some, yes. Try using "outerHeight" instead of "height" and it might work better. In any case I'll create a demo piece of code on Fiddle and send you the link.

That's a nice work anyway that you've put together here, thanks for sharing with the community.

Regards,
CM
