### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by AllThingsSmitty** [AllThingsSmitty/jquery-tips-everyone-should-know#46]
I'm setting up this card as a way to track PR's for language translations. If you're translating this repo please add a comment indicating which language so we're not duplicating work. 😎

Your PR should include the following:
1. Add a language/country code folder to the translations folder, e.g., `translations/fr-FR`
2. Add a `README.md` file with the translation to the language/country code folder, e.g., `.../fr-FR/README.md`

You can find more information about contributing under the [Language Translations](https://github.com/AllThingsSmitty/jquery-tips-everyone-should-know/blob/master/CONTRIBUTING.md#language-translations) section of the Contribution Guidelines.

I'm not looking for pasting into Google Translate; I can do that myself and it's not accurate. 💁🏼 I appreciate your help with this. 👍🏼

---

Translations (and any others that may not be on this list):
- [x] Bulgarian (bg-BG)
- [x] Chinese - simplified (zh-CN)
- [x] Chinese - traditional (zh-TW)
- [ ] Czech (cs-CZ)
- [ ] Danish (da-DK)
- [x] French (fr-FR)
- [ ] German (de-DE)
- [ ] Gujarati (gu-GU)
- [x] Hungarian (hu-HU)
- [ ] Italian (it-IT)
- [ ] Japanese (ja-JP)
- [x] Korean (ko-KR)
- [ ] Polish (pl-PL)
- [ ] Portuguese - Brazilian  (pt-BR)
- [x] Portuguese - European (pt-PT)
- [x] Russian (ru-RU)
- [x] Spanish (es-ES)
- [ ] Turkish (tr-TR)

**Comment by SamSSY** [comment]
Hi,
I am Sam Su from Taiwan, I am now working on zh-TW translation 👍 👍 👍

**Comment by AllThingsSmitty** [comment]
Thanks, @SamSSY!

**Comment by 102** [comment]
@AllThingsSmitty hi, I'll help with ru-RU translation (is it Google translated now, btw?)

**Comment by AllThingsSmitty** [comment]
@102 great, thanks! Yup, Google Translate.

**Comment by calvimor** [comment]
Hola @AllThingsSmitty,
Mi nombre es Carlos, soy de Colombia, puedo ayudar con la traducción a español. Si te parece, me avisas por favor.

**Comment by Katamori** [comment]
[Pull request for Hungarian translation.](https://github.com/AllThingsSmitty/jquery-tips-everyone-should-know/pull/50)

**Comment by danielsychoo** [comment]
Hi @AllThingsSmitty, I'm Daniel in Republic of Korea.
If you still need translation, I'll help with ko-KR. :D
