### ISSUE TITLE
Re-enabling disabled form fields

### ISSUE THREAD

**Issue by jonrmitchell** [AllThingsSmitty/jquery-tips-everyone-should-know#7]
You currently advocate `removeAttr('disabled')` for re-enabling disabled form fields. When jQuery first came out, `attr()` was the only way to modify the disabled state, and the proper way was indeed to use `removeAttr()`. Since jQuery 1.6, `prop('disabled', true)` is the right way to make an input disabled and `prop('disabled', false);` is the right way to re-eanble it (not `removeAttr('disabled')`).

http://blog.jquery.com/2011/05/10/jquery-1-6-1-rc-1-released/
https://jquery.com/upgrade-guide/1.9/#attr-versus-prop-

**Comment by AllThingsSmitty** [comment]
@jonrmitchell thanks, you're correct, I must've overlooked it.

**Comment by AllThingsSmitty** [comment]
Fixed with https://github.com/AllThingsSmitty/jquery-tips-everyone-should-know/commit/e1bec77cf093b0b3a49427cc75790886e1c2fe69.
